#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProntoV2.Resource", IsApplication=true)]

namespace ProntoV2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ProntoV2.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ProntoV2.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ProntoV2.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_green = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Camera = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Done = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int History = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int images = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int plus_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ShopNow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ShoppingIcon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001d
			public const int addBtn = 2131099677;
			
			// aapt resource value: 0x7f060013
			public const int brand = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int checkoutBtn = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int contentFrame = 2131099678;
			
			// aapt resource value: 0x7f060018
			public const int creditCardNum = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int date = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int daySpinner = 2131099674;
			
			// aapt resource value: 0x7f060000
			public const int deleteButton = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int description = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int detailsFood = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int foodCompany = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int foodIcon = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int foodName = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int foodPic = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int foodQTY = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int historyBtn = 2131099662;
			
			// aapt resource value: 0x7f060017
			public const int idText = 2131099671;
			
			// aapt resource value: 0x7f06000d
			public const int imageView1 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int main = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int minusButton = 2131099654;
			
			// aapt resource value: 0x7f060019
			public const int monthSpinner = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int plusButton = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int previewDetail = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int price = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int pricePerUnit = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int qty = 2131099660;
			
			// aapt resource value: 0x7f06001b
			public const int securityText = 2131099675;
			
			// aapt resource value: 0x7f060011
			public const int shopDetail = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int shopNowButton = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int store = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int totalPrice = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PreviousItemPreview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PreviousShoppingDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PreviousShoppingPreview = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PreviousShoppings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ReviewCheckout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ShopNowWindow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscanneractivitylayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscannerfragmentlayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
