#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProntoV2.Resource", IsApplication=true)]

namespace ProntoV2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ProntoV2.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ProntoV2.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ProntoV2.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_green = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Camera = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Done = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int History = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int images = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int plus_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ShopNow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ShoppingIcon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int X = 2131034121;
			
			// aapt resource value: 0x7f05001e
			public const int addBtn = 2131034142;
			
			// aapt resource value: 0x7f050014
			public const int brand = 2131034132;
			
			// aapt resource value: 0x7f05001d
			public const int checkoutBtn = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int contentFrame = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int creditCardNum = 2131034137;
			
			// aapt resource value: 0x7f050013
			public const int date = 2131034131;
			
			// aapt resource value: 0x7f05001b
			public const int daySpinner = 2131034139;
			
			// aapt resource value: 0x7f050000
			public const int deleteButton = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int description = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int detailsFood = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int foodCompany = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int foodIcon = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int foodName = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int foodPic = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int foodQTY = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int historyBtn = 2131034127;
			
			// aapt resource value: 0x7f050018
			public const int idText = 2131034136;
			
			// aapt resource value: 0x7f05000e
			public const int imageView1 = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int main = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int minusButton = 2131034118;
			
			// aapt resource value: 0x7f05001a
			public const int monthSpinner = 2131034138;
			
			// aapt resource value: 0x7f050008
			public const int plusButton = 2131034120;
			
			// aapt resource value: 0x7f050017
			public const int previewDetail = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int price = 2131034134;
			
			// aapt resource value: 0x7f050004
			public const int pricePerUnit = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int qty = 2131034122;
			
			// aapt resource value: 0x7f05001c
			public const int securityText = 2131034140;
			
			// aapt resource value: 0x7f050012
			public const int shopDetail = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int shopNowButton = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int store = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int totalPrice = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PreviousItemPreview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PreviousShoppingDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PreviousShoppingPreview = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PreviousShoppings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ReviewCheckout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ShopNowWindow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Temp = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
